plugins {
    id 'com.android.application'
}

android {
    compileSdk 36

    defaultConfig {
        applicationId "it.bz.tol.mofa"
        minSdk 26
        targetSdk 36
        versionCode 43
        versionName "7.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
            proguardFile 'proguard-android.txt'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt']
        }
    }
    lint {
        disable 'Typos'
        checkReleaseBuilds false
    }
    namespace 'it.schmid.android.mofa'
}

dependencies {
    implementation project(':library')
    implementation libs.ormlite.android
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.gson
    implementation libs.dropbox.android.sdk
    implementation libs.androidx.preference
    implementation libs.okhttp
    implementation libs.jsoup
}
